image:
  repository: dkrinitsyn/telegram-bot-on-llm
  pullPolicy: Always
  tag: "20260531145937"

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

env:
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.rabbitmq.svc.cluster.local/"
  DEFAULT_MODEL: "qwen3:30b-a3b-instruct-2507-q4_K_M"
  LLM_TIMEOUT: "1800"

namespace: telegram-bot-on-llm