image:
  repository: dkrinitsyn/telegram-bot-on-llm
  pullPolicy: Always
  tag: "20260425113805"

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

env:
  OLLAMA_URL: "http://kbrain:11434"

namespace: telegram-bot-on-llm